name: Push

on:
  push:
    branches-ignore:
      - dev
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.6

      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Install requirements
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes
          pip install --no-cache-dir -r requirements.txt

      - name: Run flake8
        run: flake8 .

      - name: Run pytest
        run: pytest . --no-migrations
